GET http://localhost:3000/cars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXQiOiIzMDAiLCJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJpYXQiOjE1MzAyMzUwNTh9.t9ayJtdVaEKQU0Hvnl9QLdUXuMLsNiOvWcEG9YIF4dY